[project]
name = "stm-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepdiff>=8.5.0",
    "pandas>=2.2.3",
 "pyarrow>=20.0.0",
]
